export const data = [
    { id: 1, name: 'Enoch', age: 20, hobby: 'League Player', img: "https://s3.ap-southeast-1.amazonaws.com/localiiz-prod/uploads/userimg/_300x300_crop_center-center_80_none/enoch-ngan-localiiz-intern.jpg?mtime=20221115100427&focal=none&tmtime=20240717101819"},
    { id: 2, name: 'Kyle', age: 20, hobby: 'Volleyball Enthusiast', img: "https://media.licdn.com/dms/image/D4E03AQFTclAlREqBuQ/profile-displayphoto-shrink_400_400/0/1707846540077?e=1726704000&v=beta&t=OjbgXdZWaiMM7dj-j-1O49NPGRIM9UqmVPIJZ3-8Tsc"},
    { id: 3, name: 'Quique', age: 19, hobby: 'Professional Dj', img: "https://media.licdn.com/dms/image/C5603AQHg4tdGXjEbGA/profile-displayphoto-shrink_400_400/0/1655842870090?e=1726704000&v=beta&t=SCErt189Dsw3z-6Dx-wlm9n72bhd3jeyIt6reU1jZ5Y"},
    { id: 4, name: 'Ryan', age: 20, hobby: 'Hobby: Michelle', img: "https://media.licdn.com/dms/image/D5603AQEupfDqTA7kuA/profile-displayphoto-shrink_400_400/0/1674450697965?e=1726704000&v=beta&t=v2RQIYrB5pFr8Im1_aYz4HcU21_yoePKsq2EDgKmcEs"},
];

export const users = [
    {
      fullName: 'John Johnson',
      age: '21',
      college: 'University of Washington',
      major: 'Computer Science',
      year: 'Junior',
      bedTime: '10:00 PM',
      wakeUpTime: '7:00 AM',
      guests: 'Occasionally',
      cleaning: 'Very Clean',
      studyPlace: 'Quiet Library',
      studyStyle: 'Structured',
      smoke: 'No',
      alcohol: 'Occasionally',
      dietary: 'Vegetarian',
      dietaryOther: '',
      allergies: 'None',
      img: "https://media.licdn.com/dms/image/C5603AQHg4tdGXjEbGA/profile-displayphoto-shrink_400_400/0/1655842870090?e=1726704000&v=beta&t=SCErt189Dsw3z-6Dx-wlm9n72bhd3jeyIt6reU1jZ5Y",
    },
    {
      fullName: 'Bob Smith',
      age: '22',
      college: 'Harvard University',
      major: 'Economics',
      year: 'Senior',
      bedTime: '11:00 PM',
      wakeUpTime: '6:30 AM',
      guests: 'Frequent',
      cleaning: 'Moderate',
      studyPlace: 'Coffee Shop',
      studyStyle: 'Flexible',
      smoke: 'No',
      alcohol: 'Socially',
      dietary: 'None',
      dietaryOther: '',
      allergies: 'Peanuts',
      img: "https://media.licdn.com/dms/image/D5603AQEupfDqTA7kuA/profile-displayphoto-shrink_400_400/0/1674450697965?e=1726704000&v=beta&t=v2RQIYrB5pFr8Im1_aYz4HcU21_yoePKsq2EDgKmcEs",
    },
    {
      fullName: 'Charlie Brown',
      age: '20',
      college: 'Stanford University',
      major: 'Biology',
      year: 'Sophomore',
      bedTime: '9:30 PM',
      wakeUpTime: '8:00 AM',
      guests: 'Rarely',
      cleaning: 'Very Clean',
      studyPlace: 'Dorm Room',
      studyStyle: 'Group Study',
      smoke: 'No',
      alcohol: 'No',
      dietary: 'Vegan',
      dietaryOther: '',
      allergies: 'None',
      img: "https://media.licdn.com/dms/image/C5603AQHg4tdGXjEbGA/profile-displayphoto-shrink_400_400/0/1655842870090?e=1726704000&v=beta&t=SCErt189Dsw3z-6Dx-wlm9n72bhd3jeyIt6reU1jZ5Y",
    },
    {
      fullName: 'Kevin Miller',
      age: '23',
      college: 'University of California, Berkeley',
      major: 'Political Science',
      year: 'Graduate',
      bedTime: '12:00 AM',
      wakeUpTime: '7:00 AM',
      guests: 'Occasionally',
      cleaning: 'Clean',
      studyPlace: 'Study Lounge',
      studyStyle: 'Structured',
      smoke: 'Occasionally',
      alcohol: 'Regularly',
      dietary: 'None',
      dietaryOther: '',
      allergies: 'Shellfish',
      img: "https://media.licdn.com/dms/image/D5603AQEupfDqTA7kuA/profile-displayphoto-shrink_400_400/0/1674450697965?e=1726704000&v=beta&t=v2RQIYrB5pFr8Im1_aYz4HcU21_yoePKsq2EDgKmcEs",
    },
    {
      fullName: 'Ethan Hunt',
      age: '21',
      college: 'University of Michigan',
      major: 'Engineering',
      year: 'Junior',
      bedTime: '11:30 PM',
      wakeUpTime: '6:00 AM',
      guests: 'Frequent',
      cleaning: 'Moderate',
      studyPlace: 'Library',
      studyStyle: 'Flexible',
      smoke: 'No',
      alcohol: 'Occasionally',
      dietary: 'None',
      dietaryOther: '',
      allergies: 'None',
      img: "https://media.licdn.com/dms/image/C5603AQHg4tdGXjEbGA/profile-displayphoto-shrink_400_400/0/1655842870090?e=1726704000&v=beta&t=SCErt189Dsw3z-6Dx-wlm9n72bhd3jeyIt6reU1jZ5Y",
    },
    {
      fullName: 'Allen Green',
      age: '22',
      college: 'University of Texas at Austin',
      major: 'Psychology',
      year: 'Senior',
      bedTime: '10:30 PM',
      wakeUpTime: '6:30 AM',
      guests: 'Rarely',
      cleaning: 'Very Clean',
      studyPlace: 'Quiet Study Room',
      studyStyle: 'Structured',
      smoke: 'No',
      alcohol: 'Socially',
      dietary: 'Gluten-Free',
      dietaryOther: '',
      allergies: 'None',
      img: "https://media.licdn.com/dms/image/D5603AQEupfDqTA7kuA/profile-displayphoto-shrink_400_400/0/1674450697965?e=1726704000&v=beta&t=v2RQIYrB5pFr8Im1_aYz4HcU21_yoePKsq2EDgKmcEs",
    },
    {
      fullName: 'George Black',
      age: '24',
      college: 'Columbia University',
      major: 'History',
      year: 'Graduate',
      bedTime: '1:00 AM',
      wakeUpTime: '9:00 AM',
      guests: 'Occasionally',
      cleaning: 'Clean',
      studyPlace: 'Library',
      studyStyle: 'Flexible',
      smoke: 'No',
      alcohol: 'Regularly',
      dietary: 'None',
      dietaryOther: '',
      allergies: 'Dairy',
      img: "https://media.licdn.com/dms/image/C5603AQHg4tdGXjEbGA/profile-displayphoto-shrink_400_400/0/1655842870090?e=1726704000&v=beta&t=SCErt189Dsw3z-6Dx-wlm9n72bhd3jeyIt6reU1jZ5Y",
    },
    {
      fullName: 'Walter White',
      age: '20',
      college: 'University of Florida',
      major: 'Nursing',
      year: 'Sophomore',
      bedTime: '10:00 PM',
      wakeUpTime: '6:00 AM',
      guests: 'Occasionally',
      cleaning: 'Very Clean',
      studyPlace: 'Study Lounge',
      studyStyle: 'Group Study',
      smoke: 'No',
      alcohol: 'No',
      dietary: 'Paleo',
      dietaryOther: '',
      allergies: 'None',
      img: "https://media.licdn.com/dms/image/D5603AQEupfDqTA7kuA/profile-displayphoto-shrink_400_400/0/1674450697965?e=1726704000&v=beta&t=v2RQIYrB5pFr8Im1_aYz4HcU21_yoePKsq2EDgKmcEs",
    },
    {
      fullName: 'Ian Wilson',
      age: '21',
      college: 'Princeton University',
      major: 'Physics',
      year: 'Junior',
      bedTime: '11:00 PM',
      wakeUpTime: '7:00 AM',
      guests: 'Rarely',
      cleaning: 'Moderate',
      studyPlace: 'Dorm Room',
      studyStyle: 'Structured',
      smoke: 'No',
      alcohol: 'Occasionally',
      dietary: 'None',
      dietaryOther: '',
      allergies: 'None',
      img: "https://media.licdn.com/dms/image/C5603AQHg4tdGXjEbGA/profile-displayphoto-shrink_400_400/0/1655842870090?e=1726704000&v=beta&t=SCErt189Dsw3z-6Dx-wlm9n72bhd3jeyIt6reU1jZ5Y",
    },
    {
      fullName: 'Quique Roberts',
      age: '23',
      college: 'University of California, Los Angeles',
      major: 'Art History',
      year: 'Graduate',
      bedTime: '12:00 AM',
      wakeUpTime: '8:00 AM',
      guests: 'Frequent',
      cleaning: 'Clean',
      studyPlace: 'Coffee Shop',
      studyStyle: 'Flexible',
      smoke: 'Occasionally',
      alcohol: 'Regularly',
      dietary: 'Vegetarian',
      dietaryOther: '',
      allergies: 'None',
      img: "https://media.licdn.com/dms/image/D5603AQEupfDqTA7kuA/profile-displayphoto-shrink_400_400/0/1674450697965?e=1726704000&v=beta&t=v2RQIYrB5pFr8Im1_aYz4HcU21_yoePKsq2EDgKmcEs",
    },
    {
      fullName: 'Kevin Lee',
      age: '22',
      college: 'New York University',
      major: 'Finance',
      year: 'Senior',
      bedTime: '10:30 PM',
      wakeUpTime: '7:00 AM',
      guests: 'Rarely',
      cleaning: 'Clean',
      studyPlace: 'Library',
      studyStyle: 'Structured',
      smoke: 'No',
      alcohol: 'Socially',
      dietary: 'None',
      dietaryOther: '',
      allergies: 'None',
      img: "https://media.licdn.com/dms/image/C5603AQHg4tdGXjEbGA/profile-displayphoto-shrink_400_400/0/1655842870090?e=1726704000&v=beta&t=SCErt189Dsw3z-6Dx-wlm9n72bhd3jeyIt6reU1jZ5Y",
    },
    {
      fullName: 'Nathan Smith',
      age: '20',
      college: 'University of Illinois',
      major: 'Biochemistry',
      year: 'Sophomore',
      bedTime: '11:00 PM',
      wakeUpTime: '6:30 AM',
      guests: 'Occasionally',
      cleaning: 'Very Clean',
      studyPlace: 'Quiet Study Room',
      studyStyle: 'Group Study',
      smoke: 'No',
      alcohol: 'No',
      dietary: 'Vegan',
      dietaryOther: '',
      allergies: 'None',
      img: "https://media.licdn.com/dms/image/D5603AQEupfDqTA7kuA/profile-displayphoto-shrink_400_400/0/1674450697965?e=1726704000&v=beta&t=v2RQIYrB5pFr8Im1_aYz4HcU21_yoePKsq2EDgKmcEs",
    },
];
  